/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as SharedLayoutRouteRouteImport } from './routes/_sharedLayout/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as SharedLayoutGuestRouteRouteImport } from './routes/_sharedLayout/_guest/route'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminKnowledgeRouteImport } from './routes/_auth/admin/knowledge'
import { Route as AuthAdminSummariesRouteImport } from './routes/_auth/admin/summaries'
import { Route as AuthAdminVideosRouteImport } from './routes/_auth/admin/videos'
import { Route as AuthAdminWorkRouteImport } from './routes/_auth/admin/work'
import { Route as SharedLayoutGuestLoginRouteImport } from './routes/_sharedLayout/_guest/login'
import { Route as SharedLayoutGuestSignupRouteImport } from './routes/_sharedLayout/_guest/signup'
import { Route as SharedLayoutPublicIndexRouteImport } from './routes/_sharedLayout/_public/index'
import { Route as SharedLayoutPublicKnowledgeRouteImport } from './routes/_sharedLayout/_public/knowledge'
import { Route as SharedLayoutPublicSummariesRouteImport } from './routes/_sharedLayout/_public/summaries'
import { Route as SharedLayoutPublicVideosRouteImport } from './routes/_sharedLayout/_public/videos'
import { Route as SharedLayoutPublicWorkRouteImport } from './routes/_sharedLayout/_public/work'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedLayoutRouteRoute = SharedLayoutRouteRouteImport.update({
  id: '/_sharedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SharedLayoutGuestRouteRoute = SharedLayoutGuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => SharedLayoutRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminKnowledgeRoute = AuthAdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminSummariesRoute = AuthAdminSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminVideosRoute = AuthAdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminWorkRoute = AuthAdminWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const SharedLayoutGuestLoginRoute = SharedLayoutGuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SharedLayoutGuestRouteRoute,
} as any)
const SharedLayoutGuestSignupRoute = SharedLayoutGuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => SharedLayoutGuestRouteRoute,
} as any)
const SharedLayoutPublicIndexRoute = SharedLayoutPublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => SharedLayoutRouteRoute,
} as any)
const SharedLayoutPublicKnowledgeRoute =
  SharedLayoutPublicKnowledgeRouteImport.update({
    id: '/_public/knowledge',
    path: '/knowledge',
    getParentRoute: () => SharedLayoutRouteRoute,
  } as any)
const SharedLayoutPublicSummariesRoute =
  SharedLayoutPublicSummariesRouteImport.update({
    id: '/_public/summaries',
    path: '/summaries',
    getParentRoute: () => SharedLayoutRouteRoute,
  } as any)
const SharedLayoutPublicVideosRoute =
  SharedLayoutPublicVideosRouteImport.update({
    id: '/_public/videos',
    path: '/videos',
    getParentRoute: () => SharedLayoutRouteRoute,
  } as any)
const SharedLayoutPublicWorkRoute = SharedLayoutPublicWorkRouteImport.update({
  id: '/_public/work',
  path: '/work',
  getParentRoute: () => SharedLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SharedLayoutPublicIndexRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/admin/knowledge': typeof AuthAdminKnowledgeRoute
  '/admin/summaries': typeof AuthAdminSummariesRoute
  '/admin/videos': typeof AuthAdminVideosRoute
  '/admin/work': typeof AuthAdminWorkRoute
  '/login': typeof SharedLayoutGuestLoginRoute
  '/signup': typeof SharedLayoutGuestSignupRoute
  '/knowledge': typeof SharedLayoutPublicKnowledgeRoute
  '/summaries': typeof SharedLayoutPublicSummariesRoute
  '/videos': typeof SharedLayoutPublicVideosRoute
  '/work': typeof SharedLayoutPublicWorkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SharedLayoutPublicIndexRoute
  '/admin/knowledge': typeof AuthAdminKnowledgeRoute
  '/admin/summaries': typeof AuthAdminSummariesRoute
  '/admin/videos': typeof AuthAdminVideosRoute
  '/admin/work': typeof AuthAdminWorkRoute
  '/login': typeof SharedLayoutGuestLoginRoute
  '/signup': typeof SharedLayoutGuestSignupRoute
  '/knowledge': typeof SharedLayoutPublicKnowledgeRoute
  '/summaries': typeof SharedLayoutPublicSummariesRoute
  '/videos': typeof SharedLayoutPublicVideosRoute
  '/work': typeof SharedLayoutPublicWorkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_sharedLayout': typeof SharedLayoutRouteRouteWithChildren
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_sharedLayout/_guest': typeof SharedLayoutGuestRouteRouteWithChildren
  '/_auth/admin/knowledge': typeof AuthAdminKnowledgeRoute
  '/_auth/admin/summaries': typeof AuthAdminSummariesRoute
  '/_auth/admin/videos': typeof AuthAdminVideosRoute
  '/_auth/admin/work': typeof AuthAdminWorkRoute
  '/_sharedLayout/_guest/login': typeof SharedLayoutGuestLoginRoute
  '/_sharedLayout/_guest/signup': typeof SharedLayoutGuestSignupRoute
  '/_sharedLayout/_public/knowledge': typeof SharedLayoutPublicKnowledgeRoute
  '/_sharedLayout/_public/summaries': typeof SharedLayoutPublicSummariesRoute
  '/_sharedLayout/_public/videos': typeof SharedLayoutPublicVideosRoute
  '/_sharedLayout/_public/work': typeof SharedLayoutPublicWorkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_sharedLayout/_public/': typeof SharedLayoutPublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/knowledge'
    | '/admin/summaries'
    | '/admin/videos'
    | '/admin/work'
    | '/login'
    | '/signup'
    | '/knowledge'
    | '/summaries'
    | '/videos'
    | '/work'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/knowledge'
    | '/admin/summaries'
    | '/admin/videos'
    | '/admin/work'
    | '/login'
    | '/signup'
    | '/knowledge'
    | '/summaries'
    | '/videos'
    | '/work'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/_auth'
    | '/_sharedLayout'
    | '/_auth/admin'
    | '/_sharedLayout/_guest'
    | '/_auth/admin/knowledge'
    | '/_auth/admin/summaries'
    | '/_auth/admin/videos'
    | '/_auth/admin/work'
    | '/_sharedLayout/_guest/login'
    | '/_sharedLayout/_guest/signup'
    | '/_sharedLayout/_public/knowledge'
    | '/_sharedLayout/_public/summaries'
    | '/_sharedLayout/_public/videos'
    | '/_sharedLayout/_public/work'
    | '/api/auth/$'
    | '/_auth/admin/'
    | '/_sharedLayout/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SharedLayoutRouteRoute: typeof SharedLayoutRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sharedLayout': {
      id: '/_sharedLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SharedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_sharedLayout/_guest': {
      id: '/_sharedLayout/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SharedLayoutGuestRouteRouteImport
      parentRoute: typeof SharedLayoutRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/knowledge': {
      id: '/_auth/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthAdminKnowledgeRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/summaries': {
      id: '/_auth/admin/summaries'
      path: '/summaries'
      fullPath: '/admin/summaries'
      preLoaderRoute: typeof AuthAdminSummariesRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/videos': {
      id: '/_auth/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthAdminVideosRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/work': {
      id: '/_auth/admin/work'
      path: '/work'
      fullPath: '/admin/work'
      preLoaderRoute: typeof AuthAdminWorkRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_sharedLayout/_guest/login': {
      id: '/_sharedLayout/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SharedLayoutGuestLoginRouteImport
      parentRoute: typeof SharedLayoutGuestRouteRoute
    }
    '/_sharedLayout/_guest/signup': {
      id: '/_sharedLayout/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SharedLayoutGuestSignupRouteImport
      parentRoute: typeof SharedLayoutGuestRouteRoute
    }
    '/_sharedLayout/_public/': {
      id: '/_sharedLayout/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SharedLayoutPublicIndexRouteImport
      parentRoute: typeof SharedLayoutRouteRoute
    }
    '/_sharedLayout/_public/knowledge': {
      id: '/_sharedLayout/_public/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof SharedLayoutPublicKnowledgeRouteImport
      parentRoute: typeof SharedLayoutRouteRoute
    }
    '/_sharedLayout/_public/summaries': {
      id: '/_sharedLayout/_public/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SharedLayoutPublicSummariesRouteImport
      parentRoute: typeof SharedLayoutRouteRoute
    }
    '/_sharedLayout/_public/videos': {
      id: '/_sharedLayout/_public/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof SharedLayoutPublicVideosRouteImport
      parentRoute: typeof SharedLayoutRouteRoute
    }
    '/_sharedLayout/_public/work': {
      id: '/_sharedLayout/_public/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof SharedLayoutPublicWorkRouteImport
      parentRoute: typeof SharedLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminKnowledgeRoute: typeof AuthAdminKnowledgeRoute
  AuthAdminSummariesRoute: typeof AuthAdminSummariesRoute
  AuthAdminVideosRoute: typeof AuthAdminVideosRoute
  AuthAdminWorkRoute: typeof AuthAdminWorkRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminKnowledgeRoute: AuthAdminKnowledgeRoute,
  AuthAdminSummariesRoute: AuthAdminSummariesRoute,
  AuthAdminVideosRoute: AuthAdminVideosRoute,
  AuthAdminWorkRoute: AuthAdminWorkRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SharedLayoutGuestRouteRouteChildren {
  SharedLayoutGuestLoginRoute: typeof SharedLayoutGuestLoginRoute
  SharedLayoutGuestSignupRoute: typeof SharedLayoutGuestSignupRoute
}

const SharedLayoutGuestRouteRouteChildren: SharedLayoutGuestRouteRouteChildren =
  {
    SharedLayoutGuestLoginRoute: SharedLayoutGuestLoginRoute,
    SharedLayoutGuestSignupRoute: SharedLayoutGuestSignupRoute,
  }

const SharedLayoutGuestRouteRouteWithChildren =
  SharedLayoutGuestRouteRoute._addFileChildren(
    SharedLayoutGuestRouteRouteChildren,
  )

interface SharedLayoutRouteRouteChildren {
  SharedLayoutGuestRouteRoute: typeof SharedLayoutGuestRouteRouteWithChildren
  SharedLayoutPublicKnowledgeRoute: typeof SharedLayoutPublicKnowledgeRoute
  SharedLayoutPublicSummariesRoute: typeof SharedLayoutPublicSummariesRoute
  SharedLayoutPublicVideosRoute: typeof SharedLayoutPublicVideosRoute
  SharedLayoutPublicWorkRoute: typeof SharedLayoutPublicWorkRoute
  SharedLayoutPublicIndexRoute: typeof SharedLayoutPublicIndexRoute
}

const SharedLayoutRouteRouteChildren: SharedLayoutRouteRouteChildren = {
  SharedLayoutGuestRouteRoute: SharedLayoutGuestRouteRouteWithChildren,
  SharedLayoutPublicKnowledgeRoute: SharedLayoutPublicKnowledgeRoute,
  SharedLayoutPublicSummariesRoute: SharedLayoutPublicSummariesRoute,
  SharedLayoutPublicVideosRoute: SharedLayoutPublicVideosRoute,
  SharedLayoutPublicWorkRoute: SharedLayoutPublicWorkRoute,
  SharedLayoutPublicIndexRoute: SharedLayoutPublicIndexRoute,
}

const SharedLayoutRouteRouteWithChildren =
  SharedLayoutRouteRoute._addFileChildren(SharedLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SharedLayoutRouteRoute: SharedLayoutRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
