/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicKnowledgeRouteImport } from './routes/_public/knowledge'
import { Route as PublicSummariesRouteImport } from './routes/_public/summaries'
import { Route as PublicVideosRouteImport } from './routes/_public/videos'
import { Route as PublicWorkRouteImport } from './routes/_public/work'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminKnowledgeRouteImport } from './routes/_auth/admin/knowledge'
import { Route as AuthAdminSummariesRouteImport } from './routes/_auth/admin/summaries'
import { Route as AuthAdminVideosRouteImport } from './routes/_auth/admin/videos'
import { Route as AuthAdminWorkRouteImport } from './routes/_auth/admin/work'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicKnowledgeRoute = PublicKnowledgeRouteImport.update({
  id: '/_public/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSummariesRoute = PublicSummariesRouteImport.update({
  id: '/_public/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVideosRoute = PublicVideosRouteImport.update({
  id: '/_public/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWorkRoute = PublicWorkRouteImport.update({
  id: '/_public/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminKnowledgeRoute = AuthAdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminSummariesRoute = AuthAdminSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminVideosRoute = AuthAdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminWorkRoute = AuthAdminWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/knowledge': typeof PublicKnowledgeRoute
  '/summaries': typeof PublicSummariesRoute
  '/videos': typeof PublicVideosRoute
  '/work': typeof PublicWorkRoute
  '/admin/knowledge': typeof AuthAdminKnowledgeRoute
  '/admin/summaries': typeof AuthAdminSummariesRoute
  '/admin/videos': typeof AuthAdminVideosRoute
  '/admin/work': typeof AuthAdminWorkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/knowledge': typeof PublicKnowledgeRoute
  '/summaries': typeof PublicSummariesRoute
  '/videos': typeof PublicVideosRoute
  '/work': typeof PublicWorkRoute
  '/admin/knowledge': typeof AuthAdminKnowledgeRoute
  '/admin/summaries': typeof AuthAdminSummariesRoute
  '/admin/videos': typeof AuthAdminVideosRoute
  '/admin/work': typeof AuthAdminWorkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_public/knowledge': typeof PublicKnowledgeRoute
  '/_public/summaries': typeof PublicSummariesRoute
  '/_public/videos': typeof PublicVideosRoute
  '/_public/work': typeof PublicWorkRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/admin/knowledge': typeof AuthAdminKnowledgeRoute
  '/_auth/admin/summaries': typeof AuthAdminSummariesRoute
  '/_auth/admin/videos': typeof AuthAdminVideosRoute
  '/_auth/admin/work': typeof AuthAdminWorkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/knowledge'
    | '/summaries'
    | '/videos'
    | '/work'
    | '/admin/knowledge'
    | '/admin/summaries'
    | '/admin/videos'
    | '/admin/work'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/knowledge'
    | '/summaries'
    | '/videos'
    | '/work'
    | '/admin/knowledge'
    | '/admin/summaries'
    | '/admin/videos'
    | '/admin/work'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_auth/admin'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_public/knowledge'
    | '/_public/summaries'
    | '/_public/videos'
    | '/_public/work'
    | '/_public/'
    | '/_auth/admin/knowledge'
    | '/_auth/admin/summaries'
    | '/_auth/admin/videos'
    | '/_auth/admin/work'
    | '/api/auth/$'
    | '/_auth/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  PublicKnowledgeRoute: typeof PublicKnowledgeRoute
  PublicSummariesRoute: typeof PublicSummariesRoute
  PublicVideosRoute: typeof PublicVideosRoute
  PublicWorkRoute: typeof PublicWorkRoute
  PublicIndexRoute: typeof PublicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/knowledge': {
      id: '/_public/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof PublicKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/summaries': {
      id: '/_public/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof PublicSummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/videos': {
      id: '/_public/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof PublicVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/work': {
      id: '/_public/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof PublicWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/knowledge': {
      id: '/_auth/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthAdminKnowledgeRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/summaries': {
      id: '/_auth/admin/summaries'
      path: '/summaries'
      fullPath: '/admin/summaries'
      preLoaderRoute: typeof AuthAdminSummariesRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/videos': {
      id: '/_auth/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthAdminVideosRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/work': {
      id: '/_auth/admin/work'
      path: '/work'
      fullPath: '/admin/work'
      preLoaderRoute: typeof AuthAdminWorkRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminKnowledgeRoute: typeof AuthAdminKnowledgeRoute
  AuthAdminSummariesRoute: typeof AuthAdminSummariesRoute
  AuthAdminVideosRoute: typeof AuthAdminVideosRoute
  AuthAdminWorkRoute: typeof AuthAdminWorkRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminKnowledgeRoute: AuthAdminKnowledgeRoute,
  AuthAdminSummariesRoute: AuthAdminSummariesRoute,
  AuthAdminVideosRoute: AuthAdminVideosRoute,
  AuthAdminWorkRoute: AuthAdminWorkRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  PublicKnowledgeRoute: PublicKnowledgeRoute,
  PublicSummariesRoute: PublicSummariesRoute,
  PublicVideosRoute: PublicVideosRoute,
  PublicWorkRoute: PublicWorkRoute,
  PublicIndexRoute: PublicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
